services:
  - type: web
    name: sentiai-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

  - type: web
    name: sentiai-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
